### ISSUE TITLE
Export Postman JSON to 'tools' folder

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#367]
這張是從 #352 延伸的單子

TODO:

- [x] add new folder 'tools' in BAIFI dev repo
- [x] Postman export JSON 
- [x] place it in the 'tools' folder
- [x] PR

**Comment by godmmt** [comment]
小小註記：有 PR ，標籤用 enhancement

**Comment by godmmt** [comment]
pre-commit error !

```
pretty format json.......................................................Failed
- hook id: pretty-format-json
- exit code: 1
```

**Comment by godmmt** [comment]
took 4 pt
remain 1 pt

**Comment by godmmt** [comment]
`.pre-commit-config.yaml` content:

```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: ['--autofix', '--indent', '2']
        files: '^(?:(?!tools/).)*\.json$'

```
