### ISSUE TITLE
建立 NextJS Project

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/BAIFA#410]
Steps:

- [x] learn how to create next app (read NextJS docs)
- [x] done

References from our KM & WG folder : 

1. [development-environment](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/newbie/development-environment.md)
2. [Frontend Folder Structure](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/newbie/frontend-folder-structure.md)
3. [NextJs overview](https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/NextJs/overview.md)

**Comment by godmmt** [comment]
# Next.js & How Next.js works ?

Next.js 是一個構建於 Node.js 之上的開源 Web 開發框架，支援基於 React 的 Web 應用程式功能。初始版本於 2016 年 10 月 25 日發佈。Next.js 是最流行的 React 框架之一。

Next.js 在發佈之前，會經過以下的步驟:

1. Compiling - 代碼需要轉換成瀏覽器可以理解的版本。

2. Minifying - Minifying 是在不更改代碼功能的情況下刪除不必要的代碼格式和註釋的過程。

   目標是通過減小文件大小來提高應用程式的性能。

3. Bundling - Bundling 是將 modules 合併（或“打包”）的過程，目的是減少用戶訪問網頁時對文件的請求數量。
4. Code Splitting - 是將應用程式的 bundle 分為每個 end point 所需的較小塊的過程。
   目標是通過僅加載運行該頁面所需的代碼來改進應用程式的初始加載時間。Next.js 內建了 Code Splitting 的功能。

   在建構 Next.js 網站時， pages/ 目錄中的每個文件都會自動將代碼拆分為自己的 JavaScript bundle。
   此外， 不同頁面之間共享的任何代碼也會被拆分到另一個 bundle 中，以避免在前往另一個頁面時，重新下載相同的代碼。

   在初始頁面加載後，Next.js 也會自動開始 pre-loading 用戶可能導航到的其他頁面的代碼。

- Compiling : 
![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/0c66d969-5587-45a6-a12e-1c1ef6152ea5)

- Minifying : 
![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/eae59a70-9370-4f4a-be19-2d0066eea5c2)

- Bundling : 
![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/5ea81dcb-cf95-4779-8307-3c79edc15c29)

- Code Splitting : 
  <img width="669" alt="image" src="https://github.com/CAFECA-IO/BAIFA/assets/105651918/4adab094-9953-4181-ac1b-3f0d62c01d68">

**Comment by godmmt** [comment]
# 渲染方式 React vs NextJS

React的運作方式為， 瀏覽器從伺服器接收一個空的 index.html 文件 ( 唯一的內容就是一個 id=root 的標籤
所有的 React 的內容都會放在這個標籤裡面 ) 以及用於構建 UI 的 JavaScript 程式碼。

渲染頁面內容的工作發生在用戶端的電腦設備上，這被稱為client-side rendering。

在Next.js當中，我們可以設定要使用client-side rendering還是pre-rendering。 

### pre-rendering有兩種方式：
1. Server-Side Rendering  - 
對於每個HTTP Request，網頁會重複製作。通常在需要重複向API請求即時資料的網頁會選用此種方法。 
( 像是跟股票有關的網站、即時的氣象資訊，需要每一小段時間就更新資訊的網頁 )
2. Static Site Generation -
網頁會被製作一次，並且存放在Content Delivery Networks (CDNs)的伺服器上面重複使用。( NextJS 預設且推薦的方式，
效能、SEO的表現比較好 )

- Client-Side Rendering
![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/ecfdaed5-79dc-485b-991d-b8ed3233a5b0)

- Server-Side Rendering
![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/350df20c-5f0c-4ae7-a5ae-0fa8fb93541d)

- Content Delivery Network (CDN)
![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/ebecfbac-ef48-4c95-9bd7-e949b1191dda)

**Comment by godmmt** [comment]
## References from our KM & WG folder : 

- https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/NextJs/overview.md
- https://github.com/CAFECA-IO/WorkGuidelines/blob/main/newbie/frontend-folder-structure.md

**Comment by godmmt** [comment]
took 3.5 hours

remains 8 hours

**Comment by godmmt** [comment]
# Repository : chat-bot-lizzz

- .gitignore template : Node
- License : MIT
- https://github.com/CAFECA-IO/chat-bot-lizzz

**Comment by godmmt** [comment]
create a new repo on GitHub ( set .gitignore, License; *README.md would be create by NextJS so don't create it first* )
then clone to local

cd repo
npx create-next-app --ts
ESLint - Yes
Tailwind CSS - Yes
`src` directory - Yes
App Router - Yes
import alias (@/*) - No

### git setting

```shell
code .git config
```

then set .git config : 
```
[user]
name=(the name I use at this project)
email=(GitHub email)
```

### pre-commit

```shell
brew install pre-commit
code .pre-commit-config.yaml
```

.pre-commit-config.yaml setting : 
```yaml
repos:
  - repo: <https://github.com/pre-commit/pre-commit-hooks>
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
```

```shell
pre-commit install
```

**Comment by godmmt** [comment]
### Note this:

if macOS creates a file `.DS_Store` itself,

.gitignore setting: 
```
# macOS files
.DS_Store
```

**Comment by godmmt** [comment]
### 整理資料夾結構：

根據 [Frontend Folder Structure](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/newbie/frontend-folder-structure.md) 的規則整理資料夾結構，先省略應該不會用到的 src/api & src/stores，之後會刪除沒使用到的目錄。


![image](https://github.com/CAFECA-IO/BAIFA/assets/105651918/34eeae9a-bb8f-414a-8f31-f5eb0ae0f91d)

**Comment by godmmt** [comment]
遇到 pre-commit 錯誤，無法解決，最後暫定將最後一個設置刪除。

.pre-commit-config.yaml
原先設置 : 
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
```

改為
```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
```
